Fail on main is status is failure

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -47,7 +47,8 @@ jobs:
                     if [[ "$STATUS" == "success" ]]; then
                         echo "Mocking deployment..."
                     else
-                        echo "Failed to deploy either because of doc build failure or run is not on main..."
+                        echo "Failed to deploy because doc build status is "failure"
+                        exit 1
                     fi
 
 workflows:
