Test source caching

diff --git a/.github/workflows/build-docs.yml b/.github/workflows/build-docs.yml
--- a/.github/workflows/build-docs.yml
+++ b/.github/workflows/build-docs.yml
@@ -268,29 +268,29 @@ jobs:
           path: doc/_build/html
 
   # Ensures source cache is saved if previous step fails
-  save_source_cache:
-    runs-on: ubuntu-latest
-    needs: build_docs
-    if: ${{failure()}}
-    defaults:
-      run:
-        shell: bash -el {0}
-    steps:
-      - name: Source caching
-        uses: actions/cache@v3
-        with:
-          path: .git
-          key: source-cache-${{ runner.os }}-${{ github.run_id }}
-          restore-keys: |
-            source-cache-${{ runner.os }}
-      - name: Checkout nilearn
-        uses: actions/checkout@v3
-        with:
-          ref: ${{ github.event.pull_request.head.sha }}
-          fetch-depth: 0
-      - name: Complete checkout
-        run: |
-          if ! git remote -v | grep upstream; then
-            git remote add upstream https://github.com/ymzayek/nilearn.git
-          fi
-          git fetch upstream
+#  save_source_cache:
+#    runs-on: ubuntu-latest
+#    needs: build_docs
+#    if: ${{failure()}}
+#    defaults:
+#      run:
+#        shell: bash -el {0}
+#    steps:
+#      - name: Source caching
+#        uses: actions/cache@v3
+#        with:
+#          path: .git
+#          key: source-cache-${{ runner.os }}-${{ github.run_id }}
+#          restore-keys: |
+#            source-cache-${{ runner.os }}
+#      - name: Checkout nilearn
+#        uses: actions/checkout@v3
+#        with:
+#          ref: ${{ github.event.pull_request.head.sha }}
+#          fetch-depth: 0
+#      - name: Complete checkout
+#        run: |
+#          if ! git remote -v | grep upstream; then
+#            git remote add upstream https://github.com/ymzayek/nilearn.git
+#          fi
+#          git fetch upstream
